using System;

namespace FenomPlus.Enums
{
    public class ErrorCodesEnum
    {
        public static string[] title = new string[] {
            "Test performed OK",
            "Calculating test results",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Humidity indicator turns Red",
            "Humidity indicator turns Yellow.\n status screen indicates \"F150 humidity is near low limit. Move to a higher humidity location and allow time to adjust.\"",
            "Humidity indicator turns Green",
            "",
            "Sample flow is out of tolerance. If condition persists, report error code to Customer Service.",
            "",
            "Sensor indicator turns yellow. ",
            "Device indicator turns yellow",
            "Battery indicator turns green",
            "Battery indicator turns yellow ",
            "Battery indicator turns red",
            "",
            "",
            "",
            "? Device entering sleep mode notification?",
            "? Device is not in a valid operating state?",
            "QC indicator turns green",
            "QC indicator turns yellow",
            "QC indicator turns red",
            "",
            "F150 temperature is too high.  Move F150 to cooler location and allow time to cool. (<35 C)\n,FENO testing is disabled until temperature is lowered.",
            "F150 temperature is too low.  Move F150 to wamer location and allow time to warm. (>15 C)\n,FENO testing is disabled until temperature is raised.",
            "F150 humidity is too high.  Move F150 to drier location and allow time to adjust. (<90% RH)\n,FENO testing is disabled until humidity is lowered.",
            "F150 humidity is too low.  Move F150 to higher humidity location and allow time to adjust. (>15% RH)\n,FENO testing is disabled until humidity is raised.",
            "F150 ambient pressure is too low (<76kPa).\n,FENO testing is disabled until pressure increases.",
            "F150 ambient pressure is too high (>110kPa).\n,FENO testing is disabled until pressure decreases.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Breath flow was above maximum.   Try again.",
            "Breath flow was below minimum.   Try again.",
            "Breath flow was too high. Focus on the star.",
            "Breath flow was too low. Focus on the star.",
            "Breath flow was unstable. Provide a steady and smooth flow.",
            "Breath flow did not stop fast enough.  Let go immediately at STOP.",
            "Breath flow detected after STOP.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Battery voltage is low.  Report error code to Customer Service.",
            "Battery charge is low. Connect F150 to USB-C (charge cord).",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "no device in range (BTLE) or connected",
            "BTLE is not functioning correctly. Report error code to Customer Service.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "F150 Sensor is missing.  Install a F150 sensor.",
            "F150 Sensor communication failed. Reinstall the F150 sensor and contact Customer Support if not resolved.",
            "",
            "",
            "",
            "Breath sensor is not functioning correctly.  Report error code to Customer Service.",
            "Sample flow sensor is not functioning correctly.  Report error code to Customer Service.",
            "Pressure sensor is not functioning correctly.  Report error code to Customer Service.",
            "Humidity sensor is not functioning correctly.  Report error code to Customer Service.",
            "Sample flow controller is not functioning correctly.  Report error code to Customer Service.",
            "F150 Sensor is expired.  Install a new F150 sensor.",
            "F150 is beyond its usable life.  Contact Customer Support for replacement.",
            "Sytem Error.  If restarting does not correct error code, Report error code to Customer Service.",
            "",
            "",
            ""
        };

        public static string[] code = new string[] {
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "-",
            "-",
            "-",
            "",
            "E - 101",
            "",
            "-",
            "-",
            "-",
            "-",
            "-",
            "",
            "",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "",
            "E - 201",
            "E - 202",
            "E - 203",
            "E - 204",
            "E - 205",
            "E - 206",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "E - 301",
            "E - 302",
            "E - 303",
            "E - 304",
            "E - 305",
            "E - 306",
            "E - 307",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "E - 401",
            "E - 402",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "E - 501",
            "E - 502",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "E - 701",
            "E - 702",
            "",
            "",
            "",
            "E - 705",
            "E - 706",
            "E - 707",
            "E - 708",
            "E - 709",
            "E - 703",
            "E - 704",
            "E - 710",
            "",
            "",
            ""
        };
    }
}
// 0x10